"""Constants for the sma_speedwire integration."""

DOMAIN = "sma_speedwire"

CONF_SCAN_INTERVAL = "scan_interval"
CONF_FAST_DIAGNOSTIC_INTERVAL = "fast_diagnostic_interval"
CONF_MEDIUM_DIAGNOSTIC_INTERVAL = "medium_diagnostic_interval"
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_FAST_DIAGNOSTIC_INTERVAL = 30
DEFAULT_MEDIUM_DIAGNOSTIC_INTERVAL = 60
MIN_SCAN_INTERVAL = 10
MAX_SCAN_INTERVAL = 300
MIN_FAST_DIAGNOSTIC_INTERVAL = 20
MAX_FAST_DIAGNOSTIC_INTERVAL = 600
MIN_MEDIUM_DIAGNOSTIC_INTERVAL = 30
MAX_MEDIUM_DIAGNOSTIC_INTERVAL = 3600
